GET http://localhost:5000/api/goals

###
POST http://localhost:5000/api/goals
Content-Type: application/json

{
    "text": "hello there"
}

###
PUT http://localhost:5000/api/goals/62f95f7ed758b5245f1d3bb5
Content-Type: application/json

{
    "text": "updatad goal twice"
}

###
DELETE http://localhost:5000/api/goals/62f961c5777e929f4e08560d